// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6nZIVlN-_RLhxsHgbZGAV9YEvy4FfIA',
    appId: '1:784013463168:web:e8a57f70b27fea81626065',
    messagingSenderId: '784013463168',
    projectId: 'privatenotes-hornespill',
    authDomain: 'privatenotes-hornespill.firebaseapp.com',
    storageBucket: 'privatenotes-hornespill.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEeP2tv3EIqzCmg7i7er_Ex3RNs-Cz48',
    appId: '1:784013463168:android:4d42d843b1a063eb626065',
    messagingSenderId: '784013463168',
    projectId: 'privatenotes-hornespill',
    storageBucket: 'privatenotes-hornespill.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbelz9TxcOXXbs-ZBoNkgTymo4zycxsU',
    appId: '1:784013463168:ios:e9980da54e6fd6cf626065',
    messagingSenderId: '784013463168',
    projectId: 'privatenotes-hornespill',
    storageBucket: 'privatenotes-hornespill.appspot.com',
    iosBundleId: 'andrey.dev.privatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbelz9TxcOXXbs-ZBoNkgTymo4zycxsU',
    appId: '1:784013463168:ios:22d3cfad004d9047626065',
    messagingSenderId: '784013463168',
    projectId: 'privatenotes-hornespill',
    storageBucket: 'privatenotes-hornespill.appspot.com',
    iosBundleId: 'andrey.dev.privatenotes.RunnerTests',
  );
}
